typedef enum caracteres
{
    // linhas duplas
    LINHA_VERTICAL = 186,
    LINHA_HORIZONTAL = 205,
    LINHA_VERTICAL_CENTRO = 206,
    LINHA_VERTICAL_CENTRO_ESQUERDA = 185,
    LINHA_VERTICAL_CENTRO_DIREITA = 204,
    LINHA_VERTICAL_CENTRO_CIMA = 202,
    LINHA_VERTICAL_CENTRO_BAIXO = 203,
    CANTO_SUP_DIREITO = 187,
    CANTO_SUP_ESQUERDO = 201,
    CANTO_INF_ESQUERDO = 200,
    CANTO_INF_DIREITO = 188,

    TEXTURA = 178,
} Caracteres;